---
name: "ISP Snitch"
description: "Addon for Home Assistant to track your internet connection and store it in InfluxDB"
version: "1.1.00"
url: https://github.com/stefmde/HomeAssistant-IspSnitch
slug: "isp_snitch"
init: false
startup: application
homeassistant_api: true
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  pingTestConfiguration:
    enabled: true
    debug: false
    secondsBetween: 1
    address: google.com
    timeoutMs: 1000
  speedTestConfiguration:
    enabled: true
    debug: false
    secondsBetween: 300
  influxDbSinkConfiguration:
    debug: false
    enabled: true
    storageType: Basic
  homeAssistantSinkConfiguration:
    debug: false
    enabled: true
    storageType: Basic
schema:
  pingTestConfiguration:
    enabled: bool
    debug: bool
    secondsBetween: int(1,)
    writeInfluxDbEnabled: bool
    writeToHomeAssistantEnabled: bool
    writeToHomeAssistantEverySeconds: int(1,)
    address: str
    timeoutMs: int
  speedTestConfiguration:
    enabled: bool
    debug: bool
    secondsBetween: int(60,)
    writeInfluxDbEnabled: bool
    writeToHomeAssistantEnabled: bool
    writeToHomeAssistantEverySeconds: int(1,)
    forceServerById: int(0,)?
    forceServerByHostName: str?
    forceInterfaceByName: str?
  influxDbSinkConfiguration:
    enabled: bool
    debug: bool
    storageType: list(Basic|Extended|Full)
    url: str
    token: str?
    userName: str?
    userPassword: password?
    database: str
    source: str
  homeAssistantSinkConfiguration:
    enabled: bool
    debug: bool
    storageType: list(Basic|Extended|Full)