---
name: "ISP Snitch"
description: "Addon for HomeAssistent to track your internet connection and store it in InfluxDB"
version: "1.0.21"
url: https://github.com/stefmde/HomeAssistant-IspSnitch
slug: "isp_snitch"
init: false
startup: application
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  pingTestConfiguration:
    debug: false
    enabled: true
    address: google.com
    timeoutMs: 1000
    secondsBetween: 1
  speedTestConfiguration:
    debug: false
    enabled: true
    minutesBetween: 5
  storageConfiguration:
    debug: false
    enabled: true
    storageType: Basic
schema:
  pingTestConfiguration:
    debug: bool
    enabled: bool
    address: str
    timeoutMs: int
    secondsBetween: int(1,)
  speedTestConfiguration:
    debug: bool
    enabled: bool
    minutesBetween: int(1,)
    forceServerById: int(0,)?
    forceServerByHostName: str?
    forceInterfaceByName: str?
  storageConfiguration:
    debug: bool
    enabled: bool
    url: str
    token: str?
    userName: str?
    userPassword: password?
    database: str
    storageType: list(Basic|Extended|Full)
    source: str
